# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347c0062052d5be56cc6a584458a47aa4cde2f08eaf6d1758bc06df49d53adc7617cf95dfb571024471a8b0fedf5f0b486bb4f1c1928af22ec579b2ff247cae1

test:
  secret_key_base: ef144710f6bc1ec9aa86f3619ca91ea56770b68e278f0e30163321b23e5df294e5d9acb96450567902f6cbd503220228475ca28e72e62893729dc5fe2eb9026e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'ef144710f6bc1ec9aa86f3619ca91ea56770b68e278f0e30163321b23e5df294e5d9acb96450567902f6cbd503220228475ca28e72e62893729dc5fe2eb9026e'%>
